0201:
	 g++ -o ex_0201.out -Wall -std=c++11 `pkg-config --cflags --libs opencv` ex_0201.cpp
0203:
	 g++ -o ex_0203.out -Wall -std=c++11 `pkg-config --cflags --libs opencv` ex_0203.cpp
0204:
	 g++ -o ex_0204.out -Wall -std=c++11 `pkg-config --cflags --libs opencv` ex_0204.cpp
0205:
	 g++ -o ex_0205.out -Wall -std=c++11 `pkg-config --cflags --libs opencv` ex_0205.cpp
0206:
	 g++ -o ex_0206.out -Wall -std=c++11 `pkg-config --cflags --libs opencv` ex_0206.cpp
0207:
	 g++ -o ex_0207.out -Wall -std=c++11 `pkg-config --cflags --libs opencv` ex_0207.cpp
0208:
	 g++ -o ex_0208.out -Wall -std=c++11 `pkg-config --cflags --libs opencv` ex_0208.cpp
0209:
	 g++ -o ex_0209.out -Wall -std=c++11 `pkg-config --cflags --libs opencv` ex_0209.cpp
0211:
	 g++ -o ex_0211.out -Wall -std=c++11 `pkg-config --cflags --libs opencv` ex_0211.cpp
xc0205:
	 g++ -o xc_0205.out -Wall -std=c++11 `pkg-config --cflags --libs opencv` xc_0205.cpp


clean:
	rm *.out
